### PR TITLE
🐛 Chunk sending results by size

### PR DESCRIPTION
**Pull request by jaym**
There is an upper limit to what is accepted by the platform per request. Make sure we do not go past it when sending data.

### CODE REVIEW

**Review by imilchev — COMMENTED** [review]
LGTM! I think we have similar code in cnquery though. It may be a better idea to define the chunking there so we can re-use it in both cnquery and cnspec

**Comment by jaym** [comment]
Do you have specific code in mind?

**Comment by imilchev** [comment]
Here https://github.com/mondoohq/cnquery/blob/045aa0ee10614422610a855314de93aca6841cda/mql/internal/collector.go#L31

**Comment by jaym** [comment]
https://github.com/mondoohq/cnquery/pull/4711

**Review by imilchev — APPROVED** [review]
LGTM!

**Pull request merged**
