### PR TITLE
✨ new cnspec policy command

### PR DESCRIPTION
**Pull request by mariuskimmina**
- [x] list command
  - [x] policies
  - [x] querypacks 
  - [x] file
- [x] upload command
- [x] download command
- [ ] delete command // currently unsure why this doesn't seem to work
- [x] enable command
- [x]  disable command
- [x] deprecation warning on bundle commands
- [ ] show command // section information is missing

### CODE REVIEW

**Comment by mariuskimmina** [comment]
Example deprecation warning on bundle command:

```
./cnspec bundle publish example-policy.mql.yaml --config ../server-old/server/demo.agent.credentials.json
! bundle command has been deprecated, use policy instead
→ loaded configuration from ../server-old/server/demo.agent.credentials.json using source --config
→ installing provider 'atlassian' version=9.1.12
→ successfully installed atlassian provider path=/home/marius/.config/mondoo/providers/atlassian version=9.1.12
→ load policy bundle file=example-policy.mql.yaml
→ valid policy bundle
→ add policy bundle to space space=//captain.api.mondoo.app/spaces/test-infallible-taussig-796596
→ successfully added policies
```

**Comment by mariuskimmina** [comment]
Example `policy list` command 

```
./cnspec policy list --config ../server-old/server/demo.agent.credentials.json                         on  marius/policy-subcommand [$?] via 🐹 v1.21.3 ☁️  default@mondoo-base-infra
→ loaded configuration from ../server-old/server/demo.agent.credentials.json using source --config
DISA Arista MLS DCS-7000 Series NDM STIG 1.3
  //policy.api.mondoo.app/policies/disa-stig-arista-ndm
CIS Azure Kubernetes Service (AKS) Benchmark - Level 1 1.3.0
  //policy.api.mondoo.app/policies/cis-azure-aks-level-1
CIS GitHub Benchmark - Level 1 1.0.0
  //policy.api.mondoo.app/policies/github-benchmark-level-1
CIS Amazon Elastic Kubernetes Service (EKS) Benchmark - Level 1 - Cluster / Control Plane 1.3.0
  //policy.api.mondoo.app/policies/cis-amazon-eks-cluster-control-level-1
CIS Google Kubernetes Engine (GKE) Benchmark - Level 1 1.4.0
  //policy.api.mondoo.app/policies/cis-google-gke-level-1
CIS Azure Kubernetes Service (AKS) Benchmark - Level 2 1.3.0
  //policy.api.mondoo.app/policies/cis-azure-aks-level-2
BSI SYS.1.3 Linux and Unix Servers 1.0.0
  //policy.api.mondoo.app/policies/bsi-sys13-linux-and-unix-server
  ```

**Comment by mariuskimmina** [comment]
Example `policy delete` command

```
./cnspec policy delete //policy.api.mondoo.app/policies/mondoo-soc2-inventory --config ../server-old/server/demo.agent.credentials.json
→ loaded configuration from ../server-old/server/demo.agent.credentials.json using source --config
→ successfully removed policy from space
  policy: SOC 2 Inventory Pack 1.0.0
          //policy.api.mondoo.app/policies/mondoo-soc2-inventory
  space: test-infallible-taussig-796596
          //captain.api.mondoo.app/spaces/test-infallible-taussig-796596
```

**Comment by mariuskimmina** [comment]
Example `policy show` command 

```
./cnspec policy show //policy.api.mondoo.app/policies/ubuntu-2204-level-2-server --config ../server-old/server/demo.agent.credentials.json
→ loaded configuration from ../server-old/server/demo.agent.credentials.json using source --config
→ Name:       CIS Ubuntu Linux 22.04 LTS Benchmark - Level 2 - Server
→ Version:    1.0.0
→ UID:
→ MRN:        //policy.api.mondoo.app/policies/ubuntu-2204-level-2-server
→ License:
→ Authors:    Mondoo, Inc.
→ Checks:     254
→ Description:
This document provides prescriptive guidance for establishing a secure configuration posture for Ubuntu Linux 22.04 LTS systems running on x64 platforms.

Many lists are included including filesystem types, services, clients, and network protocols. Not all items in these lists are guaranteed to exist on all distributions and additional similar i
tems may exist which should be considered in addition to those explicitly mentioned.

The guidance within broadly assumes that operations are being performed as the root user. Operations performed using sudo instead of the root user may produce unexpected results, or fail to ma
ke the intended changes to the system. Non-root users may not be able to access certain areas of the system, especially after remediation has been performed. It is advisable to verify root use
rs path integrity and the integrity of any programs being run prior to execution of commands and scripts included in this benchmark.

The guidance in this document includes changes to the running system configuration. Failure to test system configuration changes in a test environment prior to implementation on a production s
ystem could lead to loss of services.

To obtain the latest version of this guide, please visit [http://workbench.cisecurity.org](http://workbench.cisecurity.org). If you have questions, comments, or have identified ways to improve
 this guide, please write us at [feedback@cisecurity.org](mailto:feedback@cisecurity.org).
This profile extends the "Level 1 - Server" profile. Items in this profile exhibit one or more of the following characteristics:

- are intended for environments or use cases where security is paramount.
- acts as defense in depth measure.
- may negatively inhibit the utility or performance of the technology.

This profile is intended for servers.
```

**Comment by mariuskimmina** [comment]
Example `policy download` command

```
./cnspec policy download //policy.api.mondoo.app/policies/mondoo-soc2-inventory --file downloaded.yml --config ../server-old/server/demo.agent.credentials.json
→ loaded configuration from ../server-old/server/demo.agent.credentials.json using source --config
→ successfully downloaded 1 policies to the space
  policy: SOC 2 Inventory Pack 1.0.0
          //policy.api.mondoo.app/policies/mondoo-soc2-inventory
```

**Comment by imilchev** [comment]
superseded by #1033

**Pull request closed without merging**
